default: &default
  adapter: mysql2
  encoding: utf8
  reconnect: false
  pool: 5
  socket: /tmp/mysql.sock

development:
  <<: *default
  database: dev_db
  username: sasanuma_dev
  password: sasa0828

test:
  <<: *default
  database: test_db
  username: sasanuma_test
  password: sasa0828

production:
  <<: *default
  database: pro_db
  username: sasanuma_pro
  password: sasa0828
